"""Assessment generation — combines resume analysis with interview performance data."""

import re
from typing import Optional


def parse_resume_analysis(analysis_text: str) -> dict:
    """Parse the markdown resume analysis into structured sections."""
    if not analysis_text:
        return {"ats_score": 0, "strengths": [], "weaknesses": [], "missing_skills": [], "suggested_projects": []}

    result = {"ats_score": 0, "strengths": [], "weaknesses": [], "missing_skills": [], "suggested_projects": []}

    ats_match = re.search(r"ATS\s*Score[^0-9]*(\d+)", analysis_text, re.IGNORECASE)
    if ats_match:
        result["ats_score"] = int(ats_match.group(1))

    sections = re.split(r'#{1,3}\s+', analysis_text)
    for section in sections:
        if not section.strip():
            continue
        lines = section.strip().split('\n')
        heading = lines[0].strip().lower()
        content_lines = [l for l in lines[1:] if l.strip() and not l.strip().startswith('```')]

        items = []
        for s in content_lines:
            clean = re.sub(r'^[-*\d\.\s\)]+', '', s).strip()
            if clean and len(clean) > 3:
                items.append(clean)

        if 'strength' in heading:
            result["strengths"] = items
        elif 'weakness' in heading or 'area to improve' in heading:
            result["weaknesses"] = items
        elif 'missing skill' in heading:
            result["missing_skills"] = items
        elif 'suggested project' in heading:
            result["suggested_projects"] = items

    return result


def get_source_label(num_interviews: int, has_resume: bool = False) -> str:
    """Return the appropriate source attribution label based on available data."""
    if num_interviews == 0:
        return "Assessment based on resume analysis."
    elif num_interviews == 1:
        return "Assessment generated by comparing your resume and interview performance."
    return "Assessment generated using resume analysis, interview history, and performance trends."


def get_notice(num_interviews: int) -> Optional[str]:
    """Return the banner notice for resume-only or first-interview state."""
    if num_interviews == 0:
        return "Initial assessment generated from your uploaded resume. Complete interviews to receive personalized performance-based insights."
    if num_interviews == 1:
        return "This is your first interview. Future reports will compare your progress against this baseline."
    return None


def compute_readiness(parsed: dict, reports: list) -> str:
    """Compute estimated readiness level from resume ATS score or interview average."""
    if not reports:
        ats = parsed.get("ats_score", 0)
        if ats >= 80:
            return "Well Prepared"
        if ats >= 60:
            return "Moderately Prepared"
        return "Needs Preparation"

    scores = [float(r.get("overall_score", 0) or 0) for r in reports if r.get("overall_score")]
    if not scores:
        return "Unknown"
    avg = sum(scores) / len(scores)
    if avg >= 7:
        return "Well Prepared"
    if avg >= 5:
        return "Moderately Prepared"
    return "Needs Improvement"


def compute_trends(reports: list) -> dict:
    """Compute score trends across multiple interview reports (requires 2+)."""
    if len(reports) < 2:
        return {}

    scores_over_time = []
    for r in reversed(reports):
        scores_over_time.append({
            "overall": float(r.get("overall_score", 0) or 0),
            "technical": float(r.get("technical_score", 0) or 0),
            "communication": float(r.get("communication_score", 0) or 0),
            "confidence": float(r.get("confidence_score", 0) or 0),
        })

    trends = {}
    for key in ["overall", "technical", "communication", "confidence"]:
        first = scores_over_time[0][key]
        last = scores_over_time[-1][key]
        diff = last - first
        trends[key] = f"+{diff:.1f}" if diff > 0 else f"{diff:.1f}" if diff < 0 else "0.0"
    return trends


def _parse_list_items(text: str) -> list:
    """Split a comma/newline-separated string into cleaned items."""
    items = []
    for line in text.replace(",", "\n").split("\n"):
        clean = re.sub(r'^[-*\d\.\s\)]+', '', line).strip()
        if clean and len(clean) > 3:
            items.append(clean)
    return items


def compute_weaknesses(parsed: dict, reports: list, existing_db_weaknesses: list) -> list:
    """Compute combined weaknesses from resume analysis, interview reports, and tracked weaknesses."""
    weakness_map = {}

    for w in parsed.get("weaknesses", []):
        key = w.lower().strip()
        if key:
            weakness_map[key] = {"text": w, "source": "resume analysis", "count": 1, "confidence": "Medium"}

    for s in parsed.get("missing_skills", []):
        key = s.lower().strip()
        if key:
            label = f"Missing: {s}"
            weakness_map[key] = {"text": label, "source": "resume analysis", "count": 1, "confidence": "Medium"}

    for r in reports:
        w_text = (r.get("weaknesses") or "").strip()
        if w_text:
            for item in _parse_list_items(w_text):
                key = item.lower()
                if key in weakness_map:
                    weakness_map[key]["count"] += 1
                    weakness_map[key]["source"] = "interview performance"
                    weakness_map[key]["confidence"] = "High"
                else:
                    weakness_map[key] = {"text": item, "source": "interview performance", "count": 1, "confidence": "High"}

    for w in existing_db_weaknesses:
        key = (w.get("weakness_text") or "").strip().lower()
        if key and len(key) > 3:
            if key in weakness_map:
                weakness_map[key]["count"] += w.get("detected_count", 1)
                weakness_map[key]["confidence"] = "High"
            else:
                weakness_map[key] = {
                    "text": w.get("weakness_text", ""),
                    "source": "tracked",
                    "count": w.get("detected_count", 1),
                    "confidence": "High",
                    "status": w.get("status", "active"),
                }

    return sorted(weakness_map.values(), key=lambda x: x["count"], reverse=True)


def compute_strengths(parsed: dict, reports: list) -> list:
    """Compute combined strengths from resume analysis and interview reports."""
    strength_map = {}

    for s in parsed.get("strengths", []):
        key = s.lower().strip()
        if key:
            strength_map[key] = {"text": s, "source": "resume analysis", "count": 1}

    for r in reports:
        s_text = (r.get("strengths") or "").strip()
        if s_text:
            for item in _parse_list_items(s_text):
                key = item.lower()
                if key in strength_map:
                    strength_map[key]["count"] += 1
                else:
                    strength_map[key] = {"text": item, "source": "interview performance", "count": 1}

    return sorted(strength_map.values(), key=lambda x: x["count"], reverse=True)


def _average(reports: list, key: str) -> float:
    scores = [float(r.get(key, 0) or 0) for r in reports if r.get(key) is not None]
    return round(sum(scores) / len(scores), 1) if scores else 0.0


def get_assessment(parsed: dict, reports: list, existing_db_weaknesses: list) -> dict:
    """Generate complete assessment from available data sources."""
    num_interviews = len(reports)
    has_resume = bool(parsed.get("strengths") or parsed.get("ats_score", 0) > 0)
    notice = get_notice(num_interviews)
    weakness_data = compute_weaknesses(parsed, reports, existing_db_weaknesses)
    strength_data = compute_strengths(parsed, reports)

    result = {
        "source_label": get_source_label(num_interviews, has_resume),
        "notice": notice,
        "num_interviews": num_interviews,
        "has_resume": has_resume,
        "readiness": compute_readiness(parsed, reports),
        "weak_areas": weakness_data,
        "strengths": strength_data,
        "missing_skills": parsed.get("missing_skills", []),
    }

    if num_interviews > 0:
        result["average_score"] = _average(reports, "overall_score")
        result["technical_score"] = _average(reports, "technical_score")
        result["communication_score"] = _average(reports, "communication_score")
        result["confidence_score"] = _average(reports, "confidence_score")

    if num_interviews >= 2:
        result["trends"] = compute_trends(reports)

    return result
